### ISSUE TITLE
Does not run with Keras 0.3.3

### ISSUE THREAD

**Issue by PhyloStar** [maciejkula/triplet_recommendations_keras#3]
Hi,

I was testing the file with Keras 0.3.3. And it returns the following error:

``` python
Traceback (most recent call last):
  File "triplet_movielens.py", line 139, in <module>
    model = get_graph(num_users, num_items, 256)
  File "triplet_movielens.py", line 105, in get_graph
    model.compile(loss={'triplet_loss': identity_loss}, optimizer=Adam())#Adagrad(lr=0.1, epsilon=1e-06))
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 1265, in compile
    if self.outputs[self.output_order[0]].output_shape[-1] == 1:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Once I downgrade Keras to 0.3.2 and run the same file, I do not get any error.

**Comment by maciejkula** [comment]
Thanks for  the report, I noticed you opened https://github.com/fchollet/keras/issues/2201 in the Keras repo as well. I guess I'll hold off with trying things until you get a response there?

**Comment by jcpeterson** [comment]
Any update? I can't run this either, but I get a different error:

Traceback (most recent call last):
  File "model3.py", line 103, in <module>
    distance = Lambda(euclidean_distance)([processed_a, processed_b])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 485, in **call**
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 543, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 167, in create_node
    str(output_shapes))
Exception: The `get_output_shape_for` method of layer "lambda_1"" should return one shape tuple per output tensor of the layer. Found: [(None, 128), (None, 128)]

**Comment by PhyloStar** [comment]
Graph class is altogether deprecated and the Model class does the heavylifting.

**Comment by eshijia** [comment]
For the current codes, the best way to run is creating a virtualenv with installing keras 0.3.2.

**Comment by maciejkula** [comment]
Updated with https://github.com/maciejkula/triplet_recommendations_keras/pull/8
